# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root-password
ENV MYSQL_DATABASE=qp_db
ENV MYSQL_USER=db_user
ENV MYSQL_PASSWORD=db_password

# Expose the MySQL port
EXPOSE 3306
